import * as PageElements from './PageElements.mjs';
import * as ParagraphElements from './ParagraphElements.mjs';
import * as LineElements from './LineElements.mjs';

// export const s00p00ln00Animas = LineElements.page00paragraph00Lines.getAnimations();
// export const line01Animas = PageElements.page01.getAnimations({ subtree: true });
// export const line02Animas = PageElements.page02.getAnimations({ subtree: true });
// export const line03Animas = PageElements.page03.getAnimations({ subtree: true });
// export const line04Animas = PageElements.page04.getAnimations({ subtree: true });
// export const line05Animas = PageElements.page05.getAnimations({ subtree: true });
// export const line06Animas = PageElements.page06.getAnimations({ subtree: true });
// export const line07Animas = PageElements.page07.getAnimations({ subtree: true });
// export const line08Animas = PageElements.page08.getAnimations({ subtree: true });
// export const line09Animas = PageElements.page09.getAnimations({ subtree: true });
// export const line10Animas = PageElements.page10.getAnimations({ subtree: true });
// export const line11Animas = PageElements.page11.getAnimations({ subtree: true });
// export const line12Animas = PageElements.page12.getAnimations({ subtree: true });
// export const line13Animas = PageElements.page13.getAnimations({ subtree: true });
// export const line14Animas = PageElements.page14.getAnimations({ subtree: true });
// export const line15Animas = PageElements.page15.getAnimations({ subtree: true });
// export const line16Animas = PageElements.page16.getAnimations({ subtree: true });
// export const line17Animas = PageElements.page17.getAnimations({ subtree: true });
// export const line18Animas = PageElements.page18.getAnimations({ subtree: true });
// export const line19Animas = PageElements.page19.getAnimations({ subtree: true });
// export const line20Animas = PageElements.page20.getAnimations({ subtree: true });
// export const line21Animas = PageElements.page21.getAnimations({ subtree: true });
// export const line22Animas = PageElements.page22.getAnimations({ subtree: true });
// export const line23Animas = PageElements.page23.getAnimations({ subtree: true });
// export const line24Animas = PageElements.page24.getAnimations({ subtree: true });
// export const line25Animas = PageElements.page25.getAnimations({ subtree: true });
// export const line26Animas = PageElements.page26.getAnimations({ subtree: true });
// export const line27Animas = PageElements.page27.getAnimations({ subtree: true });
// export const line28Animas = PageElements.page28.getAnimations({ subtree: true });
// export const line29Animas = PageElements.page29.getAnimations({ subtree: true });
// export const line30Animas = PageElements.page30.getAnimations({ subtree: true });
// export const line31Animas = PageElements.page31.getAnimations({ subtree: true });
// export const line32Animas = PageElements.page32.getAnimations({ subtree: true });
// export const line33Animas = PageElements.page33.getAnimations({ subtree: true });
// export const line34Animas = PageElements.page34.getAnimations({ subtree: true });
